### ISSUE TITLE
Extra Move after a Goti finishes

### ISSUE THREAD

**Issue by adi-g15** [adi-g15/Ludo-The_Game#39]
Notice the Green Goti, about to finish

Earlier:

![image](https://user-images.githubusercontent.com/37269665/106321372-2e86bd80-629a-11eb-8d24-bef2fe8ac3fc.png)

After moving 1 unit (So, ek goti pung gayi, ie. one goti finished it's path):
![image](https://user-images.githubusercontent.com/37269665/106321342-23cc2880-629a-11eb-81d6-18082565efe4.png)

Expected Behaviour:
**One additional move** (if not yet finished all 4) to the player/colour whose goti finishes.

**Comment by ABHI12800** [comment]
hi @adi-g15 
I would like to take this issue, can i?

**Comment by adi-g15** [comment]
Great, assign kar dunga mai 🙂👍

Koi code clear na ho usme to can point in the issue, it's in the web/ directory.

**Comment by adi-g15** [comment]
Actually the related code is here, that handles it

https://github.com/adi-g15/Ludo-The_Game/blob/aa63e23c707263fbf83f58a7ac5258433f4fc767/web/src/App.js#L50-L56

for a head start :D

**Comment by ABHI12800** [comment]
>Hi 👋, to issue assign kar dunga mai 😁👍

Thanks @adi-g15 

>Koi code clear na ho usme to aap is issue me point kardena, it's in the web/ directory.

Sure I will let you know. :)

**Comment by ABHI12800** [comment]
Can you tell me how to setup it for web. You had only specified for `.exe` ?

**Comment by ABHI12800** [comment]
Can you tell me how to setup it for web. You had only specified for .exe .

**Comment by ABHI12800** [comment]
Can you tell me how to setup it for web. You had only specified for `.exe` ?

**Comment by ABHI12800** [comment]
Hey how to recreate the situation. Can you plz tell.

**Comment by adi-g15** [comment]
> Hey how to recreate the situation. Can you plz tell.

There is no direct way currently.

The best and easiest will just be to keep moving one goti of the colour, it doesn't take more than a minute 🙂

OR,
move() ko end ke paas ka coord paas kar sakte hai, move recieves a coordinate in form 'x-y'

Or easier than earlier, initialise position with true, just use setDie to set 'die' as a big number (only once, likely in enough to get close to home.

**Comment by ABHI12800** [comment]
Got it thanks. 😊

**Comment by adi-g15** [comment]
@ABHI12800 if you are not working on this issue currently, please state, so I can unassign this issue for now 🙂.

**Comment by ABHI12800** [comment]
Sorry, for that due to college work I was busy and will be for some time I would sure like to to work on this but for now you can unassigned the issue. 😊

**Comment by adi-g15** [comment]
> 
> 
> Sorry, for that due to college work I was busy and will be for some time I would sure like to to work on this but for now you can unassigned the issue. 😊

Okay when you want to continue, do ask and I will assign this if not assigned to anyone else 😄

**Comment by Athi223** [comment]
@adi-g15 hey brother, can I take this up? Seems like a minor change can fix this.

**Comment by adi-g15** [comment]
> @adi-g15 hey brother, can I take this up? Seems like a minor change can fix this.

Ha :smiley: :+1:

**Comment by Athi223** [comment]
@adi-g15 fixed. Although I mistakenly merged it into your master instead of mine, apologies ;-;

It was a minor fix though, so maybe you could verify it once and revert it if you find any issues.
